language: erlang
otp_release:
   - 18.1
   - 17.4
   - 17.0
   - R16B03-1
env:
   - TEST=tests
   - TEST=tests-long
   - TEST=dialyze
script: "make $TEST"
after_failure: "./tests/travis_report"
sudo: false
