sudo: false

language: erlang

script: "$TEST"

# Two stages, so that basic tests are run first
stages:
  - basic
  - test

matrix:
  fast_finish: true

  # The Travis job that checks latest OTP version is allowed to fail
  # (see relevant include below)
  allow_failures:
  - env: TEST=".travis/travis_has_latest_otp_version"

  # When otp_release is unspecified, the first value in the corresponding
  # list below will be used
  include:

  # Check that the latest Erlang version is tested

  # This test will fail with 'X' when a new version is available via kerl.
  # At that point, update THIS test's otp_release to the new one.
  # The test will keep failing with '!', until Travis has the new version.
  # When the test starts failing with 'X' again, Travis has the new version.
  # At that point, update otp_release in the corresponding list below

  - stage: basic
    otp_release: 20.3
    env: TEST=".travis/travis_has_latest_otp_version"

  # Check dialyzer
  - stage: basic
    env: TEST="make dialyze"

  # Code coverage test, that includes tests and tests-real
  - stage: test
    env: TEST="make cover"

  # Minimal support for R16B03-1
  - stage: test
    otp_release: R16B03-1
    env: TEST="make tests-real"

  # Exclude the default tests and tests-real env for latest release,
  # as the cover target includes them
  exclude:
  - otp_release: 20.2

env:
  - TEST="make tests-real"
  - TEST="make tests"

otp_release:

  # Two latest minor versions of the most recent OTP release
  # Remember to exclude the top one from the matrix above
  - 20.2
  - 20.1

  # Last minor version of older OTP releases
  - 19.3
  - 18.3
  - 17.4

  # R16B03-1 is minimally supported (see matrix section)

after_failure: "./.travis/after_failure"

before_script: "./.travis/recover_plt"
before_cache: "./.travis/store_plt"
cache:
   directories:
   - plts
