language: erlang

sudo: false

# Check README for supported versions before changing this
otp_release:
   - 19.0
   - 18.3
   - 18.2
   - 17.4
   - R16B03-1

env:
   - TEST=tests
   - TEST=tests-long
   - TEST=dialyze

matrix:
   include:
   - otp_release: R16B03-1
     env: TEST=travis_has_latest_otp_version
   allow_failures:
   - env: TEST=travis_has_latest_otp_version
   - otp_release: 19.0

script: "make -j 4 $TEST"

after_failure: "./travis/after_failure"

before_script: "./travis/recover_plt"
before_cache: "./travis/store_plt"
cache:
   directories:
   - plts
