language: erlang

sudo: false

# Check README for supported versions before changing this
otp_release:
   - 20.1
   - 20.0
   - 19.3
   - 18.3
   - 17.4
   - R16B03-1

env:
   - TEST=tests
   - TEST=tests-real

matrix:
   include:
   - env: TEST=dialyze
   - env: TEST=travis_has_latest_otp_version
   # allow_failures:
   # - env: TEST=travis_has_latest_otp_version

script: "make -j 4 $TEST"

after_failure: "./.travis/after_failure"

before_script: "./.travis/recover_plt"
before_cache: "./.travis/store_plt"
cache:
   directories:
   - plts
